# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GeekbrainsUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'
pod 'Alamofire'
pod 'Kingfisher', '~> 5.0'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Crashlytics'

  # Pods for GeekbrainsUI

end
